/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as EntryEntryIdRouteImport } from './routes/entry/$entryId'
import { Route as KoEntryEntryIdRouteImport } from './routes/ko/entry/$entryId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryEntryIdRoute = EntryEntryIdRouteImport.update({
  id: '/entry/$entryId',
  path: '/entry/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const KoEntryEntryIdRoute = KoEntryEntryIdRouteImport.update({
  id: '/ko/entry/$entryId',
  path: '/ko/entry/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/ko/': typeof KoIndexRoute
  '/ko/entry/$entryId': typeof KoEntryEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/ko': typeof KoIndexRoute
  '/ko/entry/$entryId': typeof KoEntryEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/ko/': typeof KoIndexRoute
  '/ko/entry/$entryId': typeof KoEntryEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/entry/$entryId' | '/ko/' | '/ko/entry/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/entry/$entryId' | '/ko' | '/ko/entry/$entryId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/entry/$entryId'
    | '/ko/'
    | '/ko/entry/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  EntryEntryIdRoute: typeof EntryEntryIdRoute
  KoIndexRoute: typeof KoIndexRoute
  KoEntryEntryIdRoute: typeof KoEntryEntryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$entryId': {
      id: '/entry/$entryId'
      path: '/entry/$entryId'
      fullPath: '/entry/$entryId'
      preLoaderRoute: typeof EntryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/entry/$entryId': {
      id: '/ko/entry/$entryId'
      path: '/ko/entry/$entryId'
      fullPath: '/ko/entry/$entryId'
      preLoaderRoute: typeof KoEntryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  EntryEntryIdRoute: EntryEntryIdRoute,
  KoIndexRoute: KoIndexRoute,
  KoEntryEntryIdRoute: KoEntryEntryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
