/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ConstantsRouteImport } from './routes/constants'
import { Route as BuiltWithRouteImport } from './routes/built-with'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/_index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as KoSitemapRouteImport } from './routes/ko/sitemap'
import { Route as KoSearchRouteImport } from './routes/ko/search'
import { Route as KoFavoritesRouteImport } from './routes/ko/favorites'
import { Route as KoConstantsRouteImport } from './routes/ko/constants'
import { Route as KoBuiltWithRouteImport } from './routes/ko/built-with'
import { Route as KoBrowseRouteImport } from './routes/ko/browse'
import { Route as KoAboutRouteImport } from './routes/ko/about'
import { Route as KoIndexRouteImport } from './routes/ko/_index'
import { Route as FieldFieldIdRouteImport } from './routes/field/$fieldId'
import { Route as ConceptConceptIdRouteImport } from './routes/concept/$conceptId'
import { Route as KoFieldFieldIdRouteImport } from './routes/ko/field/$fieldId'
import { Route as KoConceptConceptIdRouteImport } from './routes/ko/concept/$conceptId'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstantsRoute = ConstantsRouteImport.update({
  id: '/constants',
  path: '/constants',
  getParentRoute: () => rootRouteImport,
} as any)
const BuiltWithRoute = BuiltWithRouteImport.update({
  id: '/built-with',
  path: '/built-with',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const KoSitemapRoute = KoSitemapRouteImport.update({
  id: '/ko/sitemap',
  path: '/ko/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const KoSearchRoute = KoSearchRouteImport.update({
  id: '/ko/search',
  path: '/ko/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KoFavoritesRoute = KoFavoritesRouteImport.update({
  id: '/ko/favorites',
  path: '/ko/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const KoConstantsRoute = KoConstantsRouteImport.update({
  id: '/ko/constants',
  path: '/ko/constants',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBuiltWithRoute = KoBuiltWithRouteImport.update({
  id: '/ko/built-with',
  path: '/ko/built-with',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBrowseRoute = KoBrowseRouteImport.update({
  id: '/ko/browse',
  path: '/ko/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const KoAboutRoute = KoAboutRouteImport.update({
  id: '/ko/about',
  path: '/ko/about',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/_index',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldFieldIdRoute = FieldFieldIdRouteImport.update({
  id: '/field/$fieldId',
  path: '/field/$fieldId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptConceptIdRoute = ConceptConceptIdRouteImport.update({
  id: '/concept/$conceptId',
  path: '/concept/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const KoFieldFieldIdRoute = KoFieldFieldIdRouteImport.update({
  id: '/ko/field/$fieldId',
  path: '/ko/field/$fieldId',
  getParentRoute: () => rootRouteImport,
} as any)
const KoConceptConceptIdRoute = KoConceptConceptIdRouteImport.update({
  id: '/ko/concept/$conceptId',
  path: '/ko/concept/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/built-with': typeof BuiltWithRoute
  '/constants': typeof ConstantsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/field/$fieldId': typeof FieldFieldIdRoute
  '/ko': typeof KoIndexRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/browse': typeof KoBrowseRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/constants': typeof KoConstantsRoute
  '/ko/favorites': typeof KoFavoritesRoute
  '/ko/search': typeof KoSearchRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko/concept/$conceptId': typeof KoConceptConceptIdRoute
  '/ko/field/$fieldId': typeof KoFieldFieldIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/built-with': typeof BuiltWithRoute
  '/constants': typeof ConstantsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/field/$fieldId': typeof FieldFieldIdRoute
  '/ko': typeof KoIndexRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/browse': typeof KoBrowseRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/constants': typeof KoConstantsRoute
  '/ko/favorites': typeof KoFavoritesRoute
  '/ko/search': typeof KoSearchRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko/concept/$conceptId': typeof KoConceptConceptIdRoute
  '/ko/field/$fieldId': typeof KoFieldFieldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_index': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/built-with': typeof BuiltWithRoute
  '/constants': typeof ConstantsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/field/$fieldId': typeof FieldFieldIdRoute
  '/ko/_index': typeof KoIndexRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/browse': typeof KoBrowseRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/constants': typeof KoConstantsRoute
  '/ko/favorites': typeof KoFavoritesRoute
  '/ko/search': typeof KoSearchRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko/concept/$conceptId': typeof KoConceptConceptIdRoute
  '/ko/field/$fieldId': typeof KoFieldFieldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/about'
    | '/browse'
    | '/built-with'
    | '/constants'
    | '/favorites'
    | '/search'
    | '/sitemap'
    | '/concept/$conceptId'
    | '/field/$fieldId'
    | '/ko'
    | '/ko/about'
    | '/ko/browse'
    | '/ko/built-with'
    | '/ko/constants'
    | '/ko/favorites'
    | '/ko/search'
    | '/ko/sitemap'
    | '/ko/concept/$conceptId'
    | '/ko/field/$fieldId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/about'
    | '/browse'
    | '/built-with'
    | '/constants'
    | '/favorites'
    | '/search'
    | '/sitemap'
    | '/concept/$conceptId'
    | '/field/$fieldId'
    | '/ko'
    | '/ko/about'
    | '/ko/browse'
    | '/ko/built-with'
    | '/ko/constants'
    | '/ko/favorites'
    | '/ko/search'
    | '/ko/sitemap'
    | '/ko/concept/$conceptId'
    | '/ko/field/$fieldId'
  id:
    | '__root__'
    | '/$'
    | '/_index'
    | '/about'
    | '/browse'
    | '/built-with'
    | '/constants'
    | '/favorites'
    | '/search'
    | '/sitemap'
    | '/concept/$conceptId'
    | '/field/$fieldId'
    | '/ko/_index'
    | '/ko/about'
    | '/ko/browse'
    | '/ko/built-with'
    | '/ko/constants'
    | '/ko/favorites'
    | '/ko/search'
    | '/ko/sitemap'
    | '/ko/concept/$conceptId'
    | '/ko/field/$fieldId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  BuiltWithRoute: typeof BuiltWithRoute
  ConstantsRoute: typeof ConstantsRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  SitemapRoute: typeof SitemapRoute
  ConceptConceptIdRoute: typeof ConceptConceptIdRoute
  FieldFieldIdRoute: typeof FieldFieldIdRoute
  KoIndexRoute: typeof KoIndexRoute
  KoAboutRoute: typeof KoAboutRoute
  KoBrowseRoute: typeof KoBrowseRoute
  KoBuiltWithRoute: typeof KoBuiltWithRoute
  KoConstantsRoute: typeof KoConstantsRoute
  KoFavoritesRoute: typeof KoFavoritesRoute
  KoSearchRoute: typeof KoSearchRoute
  KoSitemapRoute: typeof KoSitemapRoute
  KoConceptConceptIdRoute: typeof KoConceptConceptIdRoute
  KoFieldFieldIdRoute: typeof KoFieldFieldIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constants': {
      id: '/constants'
      path: '/constants'
      fullPath: '/constants'
      preLoaderRoute: typeof ConstantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/built-with': {
      id: '/built-with'
      path: '/built-with'
      fullPath: '/built-with'
      preLoaderRoute: typeof BuiltWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/sitemap': {
      id: '/ko/sitemap'
      path: '/ko/sitemap'
      fullPath: '/ko/sitemap'
      preLoaderRoute: typeof KoSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/search': {
      id: '/ko/search'
      path: '/ko/search'
      fullPath: '/ko/search'
      preLoaderRoute: typeof KoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/favorites': {
      id: '/ko/favorites'
      path: '/ko/favorites'
      fullPath: '/ko/favorites'
      preLoaderRoute: typeof KoFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/constants': {
      id: '/ko/constants'
      path: '/ko/constants'
      fullPath: '/ko/constants'
      preLoaderRoute: typeof KoConstantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/built-with': {
      id: '/ko/built-with'
      path: '/ko/built-with'
      fullPath: '/ko/built-with'
      preLoaderRoute: typeof KoBuiltWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/browse': {
      id: '/ko/browse'
      path: '/ko/browse'
      fullPath: '/ko/browse'
      preLoaderRoute: typeof KoBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/about': {
      id: '/ko/about'
      path: '/ko/about'
      fullPath: '/ko/about'
      preLoaderRoute: typeof KoAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/_index': {
      id: '/ko/_index'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/$fieldId': {
      id: '/field/$fieldId'
      path: '/field/$fieldId'
      fullPath: '/field/$fieldId'
      preLoaderRoute: typeof FieldFieldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/$conceptId': {
      id: '/concept/$conceptId'
      path: '/concept/$conceptId'
      fullPath: '/concept/$conceptId'
      preLoaderRoute: typeof ConceptConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/field/$fieldId': {
      id: '/ko/field/$fieldId'
      path: '/ko/field/$fieldId'
      fullPath: '/ko/field/$fieldId'
      preLoaderRoute: typeof KoFieldFieldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/concept/$conceptId': {
      id: '/ko/concept/$conceptId'
      path: '/ko/concept/$conceptId'
      fullPath: '/ko/concept/$conceptId'
      preLoaderRoute: typeof KoConceptConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  BuiltWithRoute: BuiltWithRoute,
  ConstantsRoute: ConstantsRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  SitemapRoute: SitemapRoute,
  ConceptConceptIdRoute: ConceptConceptIdRoute,
  FieldFieldIdRoute: FieldFieldIdRoute,
  KoIndexRoute: KoIndexRoute,
  KoAboutRoute: KoAboutRoute,
  KoBrowseRoute: KoBrowseRoute,
  KoBuiltWithRoute: KoBuiltWithRoute,
  KoConstantsRoute: KoConstantsRoute,
  KoFavoritesRoute: KoFavoritesRoute,
  KoSearchRoute: KoSearchRoute,
  KoSitemapRoute: KoSitemapRoute,
  KoConceptConceptIdRoute: KoConceptConceptIdRoute,
  KoFieldFieldIdRoute: KoFieldFieldIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
