-- D1 Category Sync
-- Generated: 2026-01-16
-- Syncs categories table with apps/context/app/data/categories.json (52 categories)
-- Uses INSERT OR REPLACE to avoid conflicts

-- First, delete the old daily-life category (replaced by daily-misc)
DELETE FROM categories WHERE id = 'daily-life';

-- Insert/Replace all 52 categories
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('actions', '신체 동작', 'Body Actions', '걷기, 뛰기, 들기 등 신체 동작', 'Walking, running, lifting and other body movements', '🏃', 'red', 121);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('adjectives-basic', '기본 형용사', 'Basic Adjectives', 'TOPIK 필수 기본 형용사', 'Essential basic adjectives for TOPIK', '◆', 'purple', 18);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('adverbs', '부사/강조어', 'Adverbs & Intensifiers', '정도, 빈도, 시간 부사', 'Degree, frequency, and time adverbs', '⚡', 'yellow', 103);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('anatomy', '해부학', 'Anatomy', '근육, 뼈, 관절 등 해부학 용어', 'Muscles, bones, joints and anatomical terms', '🦴', 'purple', 122);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('art', '예술', 'Art', '미술과 예술 관련 단어', 'Art and creative expression vocabulary', '◎', 'purple', 10);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('body-misc', '신체 기타', 'Body Misc', '기타 신체 관련 어휘', 'Other body-related vocabulary', '🫁', 'purple', 126);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('body-parts', '신체 부위', 'Body Parts', '머리, 팔, 다리 등 신체 부위', 'Head, arms, legs and other body parts', '🫀', 'red', 124);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('coding', '코딩/개발', 'Coding & Development', '웹 개발, TypeScript, React, PWA 관련 용어 (RRv7 + SSG + Tailwind v4)', 'Web development, TypeScript, React, PWA terminology (RRv7 + SSG + Tailwind v4)', '⌘', 'indigo', 21);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('colors', '색상', 'Colors', '색상과 색채 관련 단어', 'Color and hue related vocabulary', '◉', 'pink', 25);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('compound-words', '복합어', 'Compound Words', '두 단어 이상이 결합된 복합어', 'Words formed by combining two or more words', '⊕', 'blue', 30);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('countries', '국가', 'Countries', '전 세계 국가와 지역의 이름', 'Names of countries and regions around the world', '◯', 'teal', 22);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('cultural-expressions', '문화 표현', 'Cultural Expressions', '한국 문화 특유의 표현', 'Uniquely Korean cultural expressions', '◈', 'red', 28);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('culture', '문화', 'Culture', '한국 문화 관련 단어', 'Korean culture related vocabulary', '◇', 'purple', 7);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('daily-misc', '일상 기타', 'Daily Misc', '기타 일상 관련 어휘', 'Other daily life vocabulary', '📋', 'teal', 116);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('education', '교육', 'Education', '교육과 학습 관련 단어', 'Education and learning vocabulary', '◻', 'blue', 35);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('emotions', '감정', 'Emotions', '감정과 기분을 표현하는 단어', 'Words expressing feelings and moods', '◐', 'pink', 2);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('events', '행사/이벤트', 'Events & Occasions', '생일, 결혼, 기념일, 모임', 'Birthdays, weddings, anniversaries, gatherings', '🎉', 'pink', 114);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('family', '가족/관계', 'Family & Relationships', '가족, 친척, 인간관계 관련 단어', 'Family, relatives, and relationship vocabulary', '∞', 'pink', 16);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('food', '음식', 'Food', '음식과 식사 관련 단어', 'Food and dining related vocabulary', '○', 'orange', 4);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('geography', '지리', 'Geography', '대륙, 바다 등 지리 관련 단어', 'Geography-related words including continents and oceans', '◐', 'teal', 24);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('gestures', '표정/제스처', 'Expressions & Gestures', '표정, 손짓, 비언어적 표현', 'Facial expressions, hand gestures, non-verbal communication', '🙌', 'orange', 123);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('greetings', '인사', 'Greetings', '일상에서 사용하는 인사말', 'Everyday greetings and salutations', '―', 'yellow', 1);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('health', '건강/상태', 'Health & Conditions', '건강, 통증, 신체 상태', 'Health, pain, physical conditions', '💊', 'green', 125);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('home', '가정/주거', 'Home & Living', '집, 가구, 가전제품', 'House, furniture, appliances', '🏠', 'indigo', 112);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('idioms', '관용구', 'Idioms', '한국어 관용 표현과 속담', 'Korean idiomatic expressions and proverbs', '≋', 'purple', 26);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('interjections', '감탄사', 'Interjections', '감정을 표현하는 감탄사', 'Exclamations expressing emotions', '!', 'yellow', 36);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('legal', '법률', 'Legal', '법률과 법적 용어', 'Legal and law related vocabulary', '§', 'indigo', 34);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('math', '수학', 'Mathematics', '수학과 계산 관련 단어', 'Mathematics and calculation vocabulary', '∑', 'teal', 14);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('medical', '의학', 'Medical', '의학과 건강 관련 단어', 'Medical and health related vocabulary', '+', 'red', 33);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('music', '음악', 'Music', '악기와 음악 관련 단어', 'Musical instruments and music vocabulary', '♪', 'red', 9);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('nouns-common', '기본 명사', 'Common Nouns', '자주 쓰이는 기본 명사', 'Frequently used common nouns', '📦', 'blue', 106);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('numbers', '숫자/시간', 'Numbers & Time', '숫자와 시간 관련 단어', 'Numbers and time related vocabulary', '#', 'green', 8);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('objects', '일상 물건', 'Everyday Objects', '개인용품, 생활용품', 'Personal items, household items', '🧴', 'green', 115);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('onomatopoeia', '의성어/의태어', 'Onomatopoeia', '소리와 모양을 흉내내는 단어', 'Sound and mimetic words', '∿', 'orange', 27);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('particles', '조사', 'Particles', '문법적 관계를 나타내는 조사', 'Grammatical particles indicating relationships', '∘', 'indigo', 23);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('phrasal-verbs', '구동사', 'Phrasal Verbs', '동사구와 복합 동사 표현', 'Verb phrases and compound verb expressions', '⇢', 'teal', 29);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('physics', '물리학', 'Physics', '물리학과 과학 관련 단어', 'Physics and science vocabulary', '∿', 'blue', 13);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('places', '장소/시설', 'Places & Facilities', '공공장소, 상업시설, 교통시설', 'Public places, shops, transportation', '🏢', 'teal', 111);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('pronouns', '대명사/지시어', 'Pronouns & Demonstratives', '인칭대명사, 지시대명사, 의문사', 'Personal pronouns, demonstratives, interrogatives', '👉', 'blue', 102);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('responses', '감탄사/응답어', 'Interjections & Responses', '감탄사, 응답어, 추임새', 'Interjections, responses, filler words', '💬', 'green', 104);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('routines', '일상 루틴', 'Daily Routines', '아침 루틴, 위생, 일상 활동', 'Morning routines, hygiene, daily activities', '🌅', 'yellow', 113);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('shopping', '쇼핑', 'Shopping', '쇼핑과 구매 관련 단어', 'Shopping and purchasing vocabulary', '▢', 'pink', 19);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('slang', '슬랭/신조어', 'Slang & Trends', '인터넷 신조어, 유행어, 줄임말', 'Internet slang, trending words, abbreviations', '🔥', 'orange', 101);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('space', '우주', 'Space', '우주와 천문학 관련 단어', 'Space and astronomy vocabulary', '☆', 'indigo', 12);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('sports', '스포츠', 'Sports', '스포츠와 운동 관련 단어', 'Sports and exercise vocabulary', '●', 'green', 11);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('time-date', '시간/날짜', 'Time & Date', '시간, 날짜, 요일 관련 단어', 'Time, date, and day-related vocabulary', '◴', 'blue', 15);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('transportation', '교통', 'Transportation', '교통수단과 이동 관련 단어', 'Transportation and travel vocabulary', '⊳', 'blue', 20);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('travel', '여행', 'Travel', '여행과 이동 관련 단어', 'Travel and transportation vocabulary', '→', 'teal', 5);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('verb-stems', '동사 어간', 'Verb Stems', '한국어 동사의 기본 어간', 'Basic stems of Korean verbs', '∨', 'green', 31);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('verbs-basic', '기본 동사', 'Basic Verbs', 'TOPIK 필수 기본 동사', 'Essential basic verbs for TOPIK', '→', 'orange', 17);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('verbs-common', '기본 동사', 'Common Verbs', '일상에서 자주 쓰는 기본 동사', 'Frequently used basic verbs', '🏃', 'purple', 105);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('work', '직장', 'Work', '직장과 비즈니스 관련 단어', 'Work and business related vocabulary', '□', 'indigo', 6);
