-- D1 Category Sync
-- Generated: 2026-01-16
-- Updates categories table to match data/context/categories.json (52 categories)
-- Uses INSERT OR REPLACE to avoid conflicts with existing data

INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('greetings', '인사', 'Greetings', '일상에서 사용하는 인사말', 'Everyday greetings and salutations', '―', 'yellow', 1);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('emotions', '감정', 'Emotions', '감정과 기분을 표현하는 단어', 'Words expressing feelings and moods', '◐', 'pink', 2);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('daily-misc', '일상생활', 'Daily Life', '일상생활에서 자주 쓰는 단어', 'Common words used in daily activities', '⌂', 'blue', 3);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('food', '음식', 'Food', '음식과 식사 관련 단어', 'Food and dining related vocabulary', '○', 'orange', 4);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('travel', '여행', 'Travel', '여행과 이동 관련 단어', 'Travel and transportation vocabulary', '→', 'teal', 5);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('work', '직장', 'Work', '직장과 비즈니스 관련 단어', 'Work and business related vocabulary', '□', 'indigo', 6);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('culture', '문화', 'Culture', '한국 문화 관련 단어', 'Korean culture related vocabulary', '◇', 'purple', 7);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('numbers', '숫자', 'Numbers', '한국어 숫자와 수 표현', 'Korean numbers and counting', '№', 'blue', 8);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('music', '음악', 'Music', '음악 관련 단어와 표현', 'Music-related vocabulary', '♪', 'purple', 9);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('art', '미술', 'Art', '미술과 예술 관련 단어', 'Art and visual arts vocabulary', '◎', 'pink', 10);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('sports', '스포츠', 'Sports', '스포츠와 운동 관련 단어', 'Sports and exercise vocabulary', '●', 'green', 11);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('space', '우주', 'Space', '우주와 천문학 관련 단어', 'Space and astronomy vocabulary', '☆', 'indigo', 12);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('physics', '물리학', 'Physics', '물리학 관련 단어', 'Physics-related vocabulary', '⚛', 'blue', 13);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('math', '수학', 'Math', '수학 관련 단어', 'Math-related vocabulary', '∑', 'teal', 14);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('time-date', '시간/날짜', 'Time & Date', '시간과 날짜 관련 표현', 'Time and date expressions', '◷', 'orange', 15);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('family', '가족', 'Family', '가족과 친척 관련 단어', 'Family and relatives vocabulary', '⌘', 'pink', 16);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('verbs-basic', '기본 동사', 'Basic Verbs', '자주 사용하는 기본 동사', 'Frequently used basic verbs', '▶', 'green', 17);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('adjectives-basic', '기본 형용사', 'Basic Adjectives', '자주 사용하는 기본 형용사', 'Frequently used basic adjectives', '◆', 'yellow', 18);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('shopping', '쇼핑', 'Shopping', '쇼핑과 구매 관련 단어', 'Shopping and purchasing vocabulary', '◈', 'orange', 19);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('transportation', '교통', 'Transportation', '교통과 이동수단 관련 단어', 'Transportation and vehicles vocabulary', '⇄', 'teal', 20);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('coding', '코딩', 'Coding', '프로그래밍과 개발 관련 단어', 'Programming and development vocabulary', '⌥', 'indigo', 21);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('countries', '나라', 'Countries', '세계 각국의 이름', 'Names of countries around the world', '⚑', 'blue', 22);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('particles', '조사', 'Particles', '한국어 조사와 어미', 'Korean particles and endings', '·', 'purple', 23);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('geography', '지리', 'Geography', '지리와 지형 관련 단어', 'Geography and terrain vocabulary', '⊕', 'green', 24);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('colors', '색깔', 'Colors', '다양한 색깔과 색상 관련 단어', 'Various colors and color-related vocabulary', '◉', 'red', 25);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('actions', '동작', 'Actions', '일상적인 동작과 행위 관련 단어', 'Common actions and activities vocabulary', '⤳', 'orange', 26);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('adverbs', '부사', 'Adverbs', '동사, 형용사를 수식하는 부사', 'Adverbs modifying verbs and adjectives', '~', 'indigo', 27);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('anatomy', '해부학', 'Anatomy', '인체 해부학 관련 단어', 'Human anatomy vocabulary', '♡', 'pink', 28);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('body-misc', '신체 기타', 'Body Misc', '신체와 관련된 기타 단어', 'Miscellaneous body-related vocabulary', '⊕', 'teal', 29);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('body-parts', '신체 부위', 'Body Parts', '신체 각 부위의 이름', 'Names of body parts', '⊙', 'pink', 30);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('compound-words', '합성어', 'Compound Words', '두 개 이상의 단어가 결합된 합성어', 'Words formed by combining two or more words', '+', 'purple', 31);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('cultural-expressions', '문화 표현', 'Cultural Expressions', '한국 문화 특유의 표현', 'Expressions unique to Korean culture', '◈', 'purple', 32);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('education', '교육', 'Education', '학교와 교육 관련 단어', 'School and education vocabulary', '📖', 'blue', 33);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('events', '행사', 'Events', '각종 행사와 이벤트 관련 단어', 'Various events and occasions vocabulary', '★', 'yellow', 34);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('gestures', '제스처', 'Gestures', '몸짓과 제스처 관련 단어', 'Body language and gesture vocabulary', '✋', 'orange', 35);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('health', '건강', 'Health', '건강과 웰빙 관련 단어', 'Health and wellness vocabulary', '✚', 'green', 36);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('home', '가정', 'Home', '집과 가정생활 관련 단어', 'Home and household vocabulary', '⌂', 'teal', 37);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('idioms', '관용어', 'Idioms', '한국어 관용 표현과 숙어', 'Korean idiomatic expressions', '≋', 'purple', 38);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('interjections', '감탄사', 'Interjections', '감정을 표현하는 감탄사', 'Exclamations expressing emotions', '!', 'yellow', 39);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('legal', '법률', 'Legal', '법률과 법적 용어', 'Legal terms and vocabulary', '§', 'indigo', 40);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('medical', '의료', 'Medical', '의료와 병원 관련 단어', 'Medical and hospital vocabulary', '⚕', 'red', 41);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('nouns-common', '일반 명사', 'Common Nouns', '일상에서 자주 쓰이는 일반 명사', 'Common nouns used in daily life', '▪', 'blue', 42);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('objects', '사물', 'Objects', '일상 사물과 물건 관련 단어', 'Everyday objects and items vocabulary', '▣', 'teal', 43);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('onomatopoeia', '의성어/의태어', 'Onomatopoeia', '소리와 모양을 흉내 내는 말', 'Words imitating sounds and appearances', '♬', 'yellow', 44);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('phrasal-verbs', '구동사', 'Phrasal Verbs', '동사와 조사가 결합된 표현', 'Verb phrases with particles', '⇢', 'orange', 45);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('places', '장소', 'Places', '다양한 장소와 위치 관련 단어', 'Various places and locations vocabulary', '⌖', 'green', 46);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('pronouns', '대명사', 'Pronouns', '명사를 대신하는 대명사', 'Words replacing nouns', '⊛', 'indigo', 47);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('responses', '대답/응답', 'Responses', '대화에서 사용하는 응답 표현', 'Response expressions in conversations', '↩', 'teal', 48);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('routines', '일과', 'Routines', '일상 루틴과 습관 관련 단어', 'Daily routines and habits vocabulary', '↻', 'blue', 49);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('slang', '속어/은어', 'Slang', '비격식 표현과 속어', 'Informal expressions and slang', '※', 'pink', 50);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('verb-stems', '동사 어간', 'Verb Stems', '동사의 기본 어간 형태', 'Base stem forms of verbs', '⊢', 'orange', 51);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('verbs-common', '일반 동사', 'Common Verbs', '자주 사용되는 일반 동사', 'Frequently used common verbs', '⊨', 'green', 52);
