-- D1 Migration: Add Korean Alphabet Categories
-- Generated: 2026-01-29
-- Adds 3 categories (consonants, vowels-basic, vowels-compound) and 35 entries

-- ============================================
-- Categories (3)
-- ============================================
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('consonants', '자음', 'Consonants', '한글 기본 자음 14개 (ㄱ~ㅎ)', '14 basic Korean consonants (ㄱ to ㅎ)', 'ㄱ', 'indigo', 53);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('vowels-basic', '기본 모음', 'Basic Vowels', '한글 기본 모음 10개 (ㅏ~ㅣ)', '10 basic Korean vowels (ㅏ to ㅣ)', 'ㅏ', 'purple', 54);
INSERT OR REPLACE INTO categories (id, name_ko, name_en, description_ko, description_en, icon, color, sort_order) VALUES ('vowels-compound', '복합 모음', 'Compound Vowels', '한글 복합 모음 11개 (ㅐ, ㅒ, ㅔ, ㅖ, ㅘ, ㅙ, ㅚ, ㅝ, ㅞ, ㅟ, ㅢ)', '11 compound Korean vowels', 'ㅐ', 'pink', 55);

-- ============================================
-- Consonant Entries (14)
-- ============================================
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('giyeok', 'ㄱ', 'giyeok', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㄱ (기역)","explanation":"한글 자음 첫 번째 글자. 혀뿌리가 목구멍을 막는 모양을 본떠 만든 글자입니다."},"en":{"word":"giyeok (ㄱ)","explanation":"The first consonant of the Korean alphabet. Pronounced like ''g'' or ''k''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('nieun', 'ㄴ', 'nieun', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㄴ (니은)","explanation":"한글 자음 두 번째 글자. 혀끝이 윗잇몸에 닿는 모양을 본떠 만든 글자입니다."},"en":{"word":"nieun (ㄴ)","explanation":"The second consonant. Pronounced like ''n''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('digeut', 'ㄷ', 'digeut', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㄷ (디귿)","explanation":"한글 자음 세 번째 글자. ㄴ에 획을 더하여 만든 글자입니다."},"en":{"word":"digeut (ㄷ)","explanation":"The third consonant. Pronounced like ''d'' or ''t''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('rieul', 'ㄹ', 'rieul', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㄹ (리을)","explanation":"한글 자음 네 번째 글자. 영어의 ''r''과 ''l'' 사이의 소리입니다."},"en":{"word":"rieul (ㄹ)","explanation":"The fourth consonant. Pronounced between ''r'' and ''l''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('mieum', 'ㅁ', 'mieum', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅁ (미음)","explanation":"한글 자음 다섯 번째 글자. 입술 모양을 본떠 만든 글자입니다."},"en":{"word":"mieum (ㅁ)","explanation":"The fifth consonant. Pronounced like ''m''. Shaped like closed lips."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('bieup', 'ㅂ', 'bieup', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅂ (비읍)","explanation":"한글 자음 여섯 번째 글자. ㅁ에 획을 더하여 만든 글자입니다."},"en":{"word":"bieup (ㅂ)","explanation":"The sixth consonant. Pronounced like ''b'' or ''p''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('siot', 'ㅅ', 'siot', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅅ (시옷)","explanation":"한글 자음 일곱 번째 글자. 이빨 모양을 본떠 만든 글자입니다."},"en":{"word":"siot (ㅅ)","explanation":"The seventh consonant. Pronounced like ''s''. Shaped like teeth."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('ieung', 'ㅇ', 'ieung', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅇ (이응)","explanation":"한글 자음 여덟 번째 글자. 초성에서는 소리가 없고, 종성에서는 ng 소리가 납니다."},"en":{"word":"ieung (ㅇ)","explanation":"The eighth consonant. Silent initially, ''ng'' sound finally."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('jieut', 'ㅈ', 'jieut', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅈ (지읒)","explanation":"한글 자음 아홉 번째 글자. ㅅ에 획을 더하여 만든 글자입니다."},"en":{"word":"jieut (ㅈ)","explanation":"The ninth consonant. Pronounced like ''j''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('chieut', 'ㅊ', 'chieut', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅊ (치읓)","explanation":"한글 자음 열 번째 글자. ㅈ의 거센소리(격음)입니다."},"en":{"word":"chieut (ㅊ)","explanation":"The tenth consonant. Aspirated ''ch'' sound."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('kieuk', 'ㅋ', 'kieuk', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅋ (키읔)","explanation":"한글 자음 열한 번째 글자. ㄱ의 거센소리(격음)입니다."},"en":{"word":"kieuk (ㅋ)","explanation":"The eleventh consonant. Aspirated ''k'' sound."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('tieut', 'ㅌ', 'tieut', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅌ (티읕)","explanation":"한글 자음 열두 번째 글자. ㄷ의 거센소리(격음)입니다."},"en":{"word":"tieut (ㅌ)","explanation":"The twelfth consonant. Aspirated ''t'' sound."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('pieup', 'ㅍ', 'pieup', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅍ (피읖)","explanation":"한글 자음 열세 번째 글자. ㅂ의 거센소리(격음)입니다."},"en":{"word":"pieup (ㅍ)","explanation":"The thirteenth consonant. Aspirated ''p'' sound."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('hieut', 'ㅎ', 'hieut', 'noun', 'consonants', 'beginner', 'common', '["alphabet","consonant"]', '{"ko":{"word":"ㅎ (히읗)","explanation":"한글 자음 마지막 글자. 목구멍에서 나오는 거친 숨소리를 나타냅니다."},"en":{"word":"hieut (ㅎ)","explanation":"The fourteenth and last consonant. Pronounced like ''h''."}}');

-- ============================================
-- Basic Vowel Entries (10)
-- ============================================
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('a-vowel', 'ㅏ', 'a', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅏ (아)","explanation":"한글 기본 모음 첫 번째 글자. 입을 크게 벌리고 내는 밝은 소리입니다."},"en":{"word":"a (ㅏ)","explanation":"First basic vowel. Pronounced ''a'' as in ''father''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('ya-vowel', 'ㅑ', 'ya', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅑ (야)","explanation":"ㅏ에서 획을 하나 더한 것으로, ''y'' 소리가 앞에 붙습니다."},"en":{"word":"ya (ㅑ)","explanation":"Second basic vowel. Pronounced ''ya'' as in ''yacht''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('eo-vowel', 'ㅓ', 'eo', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅓ (어)","explanation":"입을 조금 벌리고 내는 어두운 소리입니다. 음성 모음에 해당합니다."},"en":{"word":"eo (ㅓ)","explanation":"Third basic vowel. Pronounced like ''u'' in ''cup''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('yeo-vowel', 'ㅕ', 'yeo', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅕ (여)","explanation":"ㅓ에서 획을 하나 더한 것으로, ''y'' 소리가 앞에 붙습니다."},"en":{"word":"yeo (ㅕ)","explanation":"Fourth basic vowel. Pronounced ''yuh''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('o-vowel', 'ㅗ', 'o', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅗ (오)","explanation":"입술을 둥글게 오므리고 내는 소리입니다. 양성 모음에 해당합니다."},"en":{"word":"o (ㅗ)","explanation":"Fifth basic vowel. Pronounced ''oh'' as in ''go''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('yo-vowel', 'ㅛ', 'yo', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅛ (요)","explanation":"ㅗ에서 획을 하나 더한 것으로, ''y'' 소리가 앞에 붙습니다."},"en":{"word":"yo (ㅛ)","explanation":"Sixth basic vowel. Pronounced ''yo'' as in ''yoga''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('u-vowel', 'ㅜ', 'u', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅜ (우)","explanation":"입술을 둥글게 오므리고 앞으로 내밀어 내는 소리입니다."},"en":{"word":"u (ㅜ)","explanation":"Seventh basic vowel. Pronounced ''oo'' as in ''moon''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('yu-vowel', 'ㅠ', 'yu', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅠ (유)","explanation":"ㅜ에서 획을 하나 더한 것으로, ''y'' 소리가 앞에 붙습니다."},"en":{"word":"yu (ㅠ)","explanation":"Eighth basic vowel. Pronounced ''yoo''. ㅠㅠ means crying online."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('eu-vowel', 'ㅡ', 'eu', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅡ (으)","explanation":"입을 옆으로 벌리고 내는 소리로, 영어에 없는 독특한 한국어 모음입니다."},"en":{"word":"eu (ㅡ)","explanation":"Ninth basic vowel. No English equivalent. Spread lips and say ''oo''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('i-vowel', 'ㅣ', 'i', 'noun', 'vowels-basic', 'beginner', 'common', '["alphabet","vowel"]', '{"ko":{"word":"ㅣ (이)","explanation":"한글 기본 모음 마지막 글자. 훈민정음에서 사람을 상징합니다."},"en":{"word":"i (ㅣ)","explanation":"Tenth and last basic vowel. Pronounced ''ee'' as in ''see''."}}');

-- ============================================
-- Compound Vowel Entries (11)
-- ============================================
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('ae-vowel', 'ㅐ', 'ae', 'noun', 'vowels-compound', 'beginner', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅐ (애)","explanation":"ㅏ와 ㅣ가 합쳐진 복합 모음입니다. 현대 한국어에서는 ㅔ와 거의 같은 소리입니다."},"en":{"word":"ae (ㅐ)","explanation":"Compound vowel (ㅏ+ㅣ). Pronounced like ''e'' in ''bed''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('yae-vowel', 'ㅒ', 'yae', 'noun', 'vowels-compound', 'beginner', 'rare', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅒ (얘)","explanation":"ㅑ와 ㅣ가 합쳐진 복합 모음입니다. 사용 빈도가 낮습니다."},"en":{"word":"yae (ㅒ)","explanation":"Compound vowel (ㅑ+ㅣ). Pronounced ''yeh''. Rarely used."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('e-vowel', 'ㅔ', 'e', 'noun', 'vowels-compound', 'beginner', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅔ (에)","explanation":"ㅓ와 ㅣ가 합쳐진 복합 모음입니다. ㅐ와 거의 같은 소리입니다."},"en":{"word":"e (ㅔ)","explanation":"Compound vowel (ㅓ+ㅣ). Pronounced like ''e'' in ''bed''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('ye-vowel', 'ㅖ', 'ye', 'noun', 'vowels-compound', 'beginner', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅖ (예)","explanation":"ㅕ와 ㅣ가 합쳐진 복합 모음입니다. ''예'' (yes)에서 자주 쓰입니다."},"en":{"word":"ye (ㅖ)","explanation":"Compound vowel (ㅕ+ㅣ). Pronounced ''yeh''. Used in ''예'' (yes)."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('wa-vowel', 'ㅘ', 'wa', 'noun', 'vowels-compound', 'beginner', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅘ (와)","explanation":"ㅗ와 ㅏ가 합쳐진 복합 모음입니다."},"en":{"word":"wa (ㅘ)","explanation":"Compound vowel (ㅗ+ㅏ). Pronounced ''wa'' as in ''wand''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('wae-vowel', 'ㅙ', 'wae', 'noun', 'vowels-compound', 'intermediate', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅙ (왜)","explanation":"ㅗ와 ㅐ가 합쳐진 복합 모음입니다. ''왜'' (why)에서 자주 쓰입니다."},"en":{"word":"wae (ㅙ)","explanation":"Compound vowel (ㅗ+ㅐ). Pronounced ''weh''. Used in ''왜'' (why)."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('oe-vowel', 'ㅚ', 'oe', 'noun', 'vowels-compound', 'intermediate', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅚ (외)","explanation":"ㅗ와 ㅣ가 합쳐진 복합 모음입니다. 현대에는 [we]로 발음됩니다."},"en":{"word":"oe (ㅚ)","explanation":"Compound vowel (ㅗ+ㅣ). Now pronounced [we] in modern Korean."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('wo-vowel', 'ㅝ', 'wo', 'noun', 'vowels-compound', 'beginner', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅝ (워)","explanation":"ㅜ와 ㅓ가 합쳐진 복합 모음입니다."},"en":{"word":"wo (ㅝ)","explanation":"Compound vowel (ㅜ+ㅓ). Pronounced ''wuh''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('we-vowel', 'ㅞ', 'we', 'noun', 'vowels-compound', 'intermediate', 'rare', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅞ (웨)","explanation":"ㅜ와 ㅔ가 합쳐진 복합 모음입니다. 주로 외래어에 쓰입니다."},"en":{"word":"we (ㅞ)","explanation":"Compound vowel (ㅜ+ㅔ). Pronounced ''weh''. Mainly in loanwords."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('wi-vowel', 'ㅟ', 'wi', 'noun', 'vowels-compound', 'beginner', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅟ (위)","explanation":"ㅜ와 ㅣ가 합쳐진 복합 모음입니다."},"en":{"word":"wi (ㅟ)","explanation":"Compound vowel (ㅜ+ㅣ). Pronounced ''wee''."}}');
INSERT OR REPLACE INTO entries (id, korean, romanization, part_of_speech, category_id, difficulty, frequency, tags, translations) VALUES ('ui-vowel', 'ㅢ', 'ui', 'noun', 'vowels-compound', 'intermediate', 'common', '["alphabet","vowel","compound"]', '{"ko":{"word":"ㅢ (의)","explanation":"ㅡ와 ㅣ가 합쳐진 복합 모음입니다. 위치에 따라 발음이 3가지로 변합니다."},"en":{"word":"ui (ㅢ)","explanation":"Compound vowel (ㅡ+ㅣ). Has 3 pronunciations depending on position."}}');
