/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebApiRouteImport } from './routes/web-api'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as LibrariesRouteImport } from './routes/libraries'
import { Route as BuiltWithRouteImport } from './routes/built-with'
import { Route as IndexRouteImport } from './routes/_index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as WebApiSlugRouteImport } from './routes/web-api/$slug'
import { Route as LibrarySlugRouteImport } from './routes/library/$slug'
import { Route as KoWebApiRouteImport } from './routes/ko/web-api'
import { Route as KoSitemapRouteImport } from './routes/ko/sitemap'
import { Route as KoLibrariesRouteImport } from './routes/ko/libraries'
import { Route as KoBuiltWithRouteImport } from './routes/ko/built-with'
import { Route as KoIndexRouteImport } from './routes/ko/_index'
import { Route as CategoryCategoryIdRouteImport } from './routes/category/$categoryId'
import { Route as KoWebApiSlugRouteImport } from './routes/ko/web-api/$slug'
import { Route as KoLibrarySlugRouteImport } from './routes/ko/library/$slug'
import { Route as KoCategoryCategoryIdRouteImport } from './routes/ko/category/$categoryId'

const WebApiRoute = WebApiRouteImport.update({
  id: '/web-api',
  path: '/web-api',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRoute = LibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const BuiltWithRoute = BuiltWithRouteImport.update({
  id: '/built-with',
  path: '/built-with',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WebApiSlugRoute = WebApiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WebApiRoute,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KoWebApiRoute = KoWebApiRouteImport.update({
  id: '/ko/web-api',
  path: '/ko/web-api',
  getParentRoute: () => rootRouteImport,
} as any)
const KoSitemapRoute = KoSitemapRouteImport.update({
  id: '/ko/sitemap',
  path: '/ko/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const KoLibrariesRoute = KoLibrariesRouteImport.update({
  id: '/ko/libraries',
  path: '/ko/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBuiltWithRoute = KoBuiltWithRouteImport.update({
  id: '/ko/built-with',
  path: '/ko/built-with',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/_index',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const KoWebApiSlugRoute = KoWebApiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KoWebApiRoute,
} as any)
const KoLibrarySlugRoute = KoLibrarySlugRouteImport.update({
  id: '/ko/library/$slug',
  path: '/ko/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KoCategoryCategoryIdRoute = KoCategoryCategoryIdRouteImport.update({
  id: '/ko/category/$categoryId',
  path: '/ko/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof IndexRoute
  '/built-with': typeof BuiltWithRoute
  '/libraries': typeof LibrariesRoute
  '/sitemap': typeof SitemapRoute
  '/web-api': typeof WebApiRouteWithChildren
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/ko': typeof KoIndexRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/libraries': typeof KoLibrariesRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko/web-api': typeof KoWebApiRouteWithChildren
  '/library/$slug': typeof LibrarySlugRoute
  '/web-api/$slug': typeof WebApiSlugRoute
  '/ko/category/$categoryId': typeof KoCategoryCategoryIdRoute
  '/ko/library/$slug': typeof KoLibrarySlugRoute
  '/ko/web-api/$slug': typeof KoWebApiSlugRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof IndexRoute
  '/built-with': typeof BuiltWithRoute
  '/libraries': typeof LibrariesRoute
  '/sitemap': typeof SitemapRoute
  '/web-api': typeof WebApiRouteWithChildren
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/ko': typeof KoIndexRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/libraries': typeof KoLibrariesRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko/web-api': typeof KoWebApiRouteWithChildren
  '/library/$slug': typeof LibrarySlugRoute
  '/web-api/$slug': typeof WebApiSlugRoute
  '/ko/category/$categoryId': typeof KoCategoryCategoryIdRoute
  '/ko/library/$slug': typeof KoLibrarySlugRoute
  '/ko/web-api/$slug': typeof KoWebApiSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_index': typeof IndexRoute
  '/built-with': typeof BuiltWithRoute
  '/libraries': typeof LibrariesRoute
  '/sitemap': typeof SitemapRoute
  '/web-api': typeof WebApiRouteWithChildren
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/ko/_index': typeof KoIndexRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/libraries': typeof KoLibrariesRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko/web-api': typeof KoWebApiRouteWithChildren
  '/library/$slug': typeof LibrarySlugRoute
  '/web-api/$slug': typeof WebApiSlugRoute
  '/ko/category/$categoryId': typeof KoCategoryCategoryIdRoute
  '/ko/library/$slug': typeof KoLibrarySlugRoute
  '/ko/web-api/$slug': typeof KoWebApiSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/built-with'
    | '/libraries'
    | '/sitemap'
    | '/web-api'
    | '/category/$categoryId'
    | '/ko'
    | '/ko/built-with'
    | '/ko/libraries'
    | '/ko/sitemap'
    | '/ko/web-api'
    | '/library/$slug'
    | '/web-api/$slug'
    | '/ko/category/$categoryId'
    | '/ko/library/$slug'
    | '/ko/web-api/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/built-with'
    | '/libraries'
    | '/sitemap'
    | '/web-api'
    | '/category/$categoryId'
    | '/ko'
    | '/ko/built-with'
    | '/ko/libraries'
    | '/ko/sitemap'
    | '/ko/web-api'
    | '/library/$slug'
    | '/web-api/$slug'
    | '/ko/category/$categoryId'
    | '/ko/library/$slug'
    | '/ko/web-api/$slug'
  id:
    | '__root__'
    | '/$'
    | '/_index'
    | '/built-with'
    | '/libraries'
    | '/sitemap'
    | '/web-api'
    | '/category/$categoryId'
    | '/ko/_index'
    | '/ko/built-with'
    | '/ko/libraries'
    | '/ko/sitemap'
    | '/ko/web-api'
    | '/library/$slug'
    | '/web-api/$slug'
    | '/ko/category/$categoryId'
    | '/ko/library/$slug'
    | '/ko/web-api/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  IndexRoute: typeof IndexRoute
  BuiltWithRoute: typeof BuiltWithRoute
  LibrariesRoute: typeof LibrariesRoute
  SitemapRoute: typeof SitemapRoute
  WebApiRoute: typeof WebApiRouteWithChildren
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  KoIndexRoute: typeof KoIndexRoute
  KoBuiltWithRoute: typeof KoBuiltWithRoute
  KoLibrariesRoute: typeof KoLibrariesRoute
  KoSitemapRoute: typeof KoSitemapRoute
  KoWebApiRoute: typeof KoWebApiRouteWithChildren
  LibrarySlugRoute: typeof LibrarySlugRoute
  KoCategoryCategoryIdRoute: typeof KoCategoryCategoryIdRoute
  KoLibrarySlugRoute: typeof KoLibrarySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-api': {
      id: '/web-api'
      path: '/web-api'
      fullPath: '/web-api'
      preLoaderRoute: typeof WebApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/built-with': {
      id: '/built-with'
      path: '/built-with'
      fullPath: '/built-with'
      preLoaderRoute: typeof BuiltWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-api/$slug': {
      id: '/web-api/$slug'
      path: '/$slug'
      fullPath: '/web-api/$slug'
      preLoaderRoute: typeof WebApiSlugRouteImport
      parentRoute: typeof WebApiRoute
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/web-api': {
      id: '/ko/web-api'
      path: '/ko/web-api'
      fullPath: '/ko/web-api'
      preLoaderRoute: typeof KoWebApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/sitemap': {
      id: '/ko/sitemap'
      path: '/ko/sitemap'
      fullPath: '/ko/sitemap'
      preLoaderRoute: typeof KoSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/libraries': {
      id: '/ko/libraries'
      path: '/ko/libraries'
      fullPath: '/ko/libraries'
      preLoaderRoute: typeof KoLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/built-with': {
      id: '/ko/built-with'
      path: '/ko/built-with'
      fullPath: '/ko/built-with'
      preLoaderRoute: typeof KoBuiltWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/_index': {
      id: '/ko/_index'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/web-api/$slug': {
      id: '/ko/web-api/$slug'
      path: '/$slug'
      fullPath: '/ko/web-api/$slug'
      preLoaderRoute: typeof KoWebApiSlugRouteImport
      parentRoute: typeof KoWebApiRoute
    }
    '/ko/library/$slug': {
      id: '/ko/library/$slug'
      path: '/ko/library/$slug'
      fullPath: '/ko/library/$slug'
      preLoaderRoute: typeof KoLibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/category/$categoryId': {
      id: '/ko/category/$categoryId'
      path: '/ko/category/$categoryId'
      fullPath: '/ko/category/$categoryId'
      preLoaderRoute: typeof KoCategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WebApiRouteChildren {
  WebApiSlugRoute: typeof WebApiSlugRoute
}

const WebApiRouteChildren: WebApiRouteChildren = {
  WebApiSlugRoute: WebApiSlugRoute,
}

const WebApiRouteWithChildren =
  WebApiRoute._addFileChildren(WebApiRouteChildren)

interface KoWebApiRouteChildren {
  KoWebApiSlugRoute: typeof KoWebApiSlugRoute
}

const KoWebApiRouteChildren: KoWebApiRouteChildren = {
  KoWebApiSlugRoute: KoWebApiSlugRoute,
}

const KoWebApiRouteWithChildren = KoWebApiRoute._addFileChildren(
  KoWebApiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  IndexRoute: IndexRoute,
  BuiltWithRoute: BuiltWithRoute,
  LibrariesRoute: LibrariesRoute,
  SitemapRoute: SitemapRoute,
  WebApiRoute: WebApiRouteWithChildren,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  KoIndexRoute: KoIndexRoute,
  KoBuiltWithRoute: KoBuiltWithRoute,
  KoLibrariesRoute: KoLibrariesRoute,
  KoSitemapRoute: KoSitemapRoute,
  KoWebApiRoute: KoWebApiRouteWithChildren,
  LibrarySlugRoute: LibrarySlugRoute,
  KoCategoryCategoryIdRoute: KoCategoryCategoryIdRoute,
  KoLibrarySlugRoute: KoLibrarySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
