// typed-scss-modules configuration
// Generates .d.ts files for SCSS modules to enable TypeScript autocomplete

/** @type {import('typed-scss-modules').Config} */
export default {
  // Export type: default export (matches current usage pattern)
  exportType: 'default',

  // Name format: camelCase (React convention)
  nameFormat: ['camel'],

  // Use sass implementation (already installed)
  implementation: 'sass',

  // Quote type: single (matches Biome config)
  quoteType: 'single',

  // Include paths for SCSS imports
  includePaths: ['packages/shared/src/styles', 'packages/shared-react/src/styles'],

  // Log level
  logLevel: 'info',

  // Banner for generated files
  banner: '// This file is auto-generated by typed-scss-modules. Do not edit.',
};
