import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Config } from '@react-router/dev/config';
import { extractStaticRoutes, generateI18nRoutes } from '@soundblue/i18n';
import routes from './app/routes.js';

/**
 * Concept names lookup: concept ID → localized names
 * Matches the structure generated by prebuild script
 */
type ConceptNamesJson = Record<string, { ko: string; en: string }>;

/**
 * React Router SSG 설정
 *
 * ## Single Source of Truth
 * - 정적 라우트: routes.ts에서 자동 추출 (extractStaticRoutes)
 * - 동적 라우트: 데이터 기반 생성 (generateI18nRoutes)
 */
export default {
  ssr: false, // 100% SSG - no SSR, only static files
  async prerender() {
    // 정적 라우트: routes.ts에서 자동 추출
    const staticRoutes = extractStaticRoutes(routes);

    // 동적 라우트: 데이터 기반 생성
    const { fields } = await import('./app/data/fields.js');
    const conceptNamesPath = join(process.cwd(), 'public', 'concept-names.json');
    const conceptNames: ConceptNamesJson = JSON.parse(readFileSync(conceptNamesPath, 'utf-8'));
    const conceptIds = Object.keys(conceptNames);

    const conceptRoutes = generateI18nRoutes(conceptIds, (conceptId) => `/concept/${conceptId}`);
    const fieldRoutes = generateI18nRoutes(fields, (field) => `/field/${field.id}`);

    return [...staticRoutes, ...conceptRoutes, ...fieldRoutes];
  },
} satisfies Config;
