/**
 * Sitemap Generator for Roots App
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createDynamicUrls, generateSitemaps, type StaticPage } from '@soundblue/seo/sitemap';
import { fields } from '../app/data/fields';

/**
 * Concept names lookup: concept ID → localized names
 * Matches the structure generated by prebuild script
 */
type ConceptNamesJson = Record<string, { ko: string; en: string }>;

const __dirname = dirname(fileURLToPath(import.meta.url));

const CONFIG = {
  siteUrl: 'https://roots.soundbluemusic.com',
  languages: ['en', 'ko'] as const,
  appName: 'Roots',
  appSubtitle: 'Roots - Math Documentation for Learners',
  outputDir: join(__dirname, '../public'),
  buildOutputDir: join(__dirname, '../build/client'),
};

const STATIC_PAGES: StaticPage[] = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/browse', priority: '0.9', changefreq: 'weekly' },
  { path: '/search', priority: '0.9', changefreq: 'weekly' },
  { path: '/favorites', priority: '0.8', changefreq: 'daily' },
  { path: '/constants', priority: '0.8', changefreq: 'monthly' },
  { path: '/about', priority: '0.5', changefreq: 'monthly' },
  { path: '/sitemap', priority: '0.5', changefreq: 'monthly' },
];

// Load concept IDs from concept-names.json (generated by prebuild)
const conceptNamesPath = join(CONFIG.outputDir, 'concept-names.json');
const conceptNames: ConceptNamesJson = JSON.parse(readFileSync(conceptNamesPath, 'utf-8'));
const conceptIds = Object.keys(conceptNames);

// Trailing slash required for Cloudflare Workers Assets
// Workers Assets serves folder/index.html with 307 redirect to folder/
// Sitemap URLs must match the final canonical URL with trailing slash
const TRAILING_SLASH = true;

generateSitemaps(CONFIG, STATIC_PAGES, [
  {
    name: 'concepts',
    urls: createDynamicUrls(
      CONFIG.siteUrl,
      '/concept',
      conceptIds,
      '0.7',
      'monthly',
      CONFIG.languages,
      TRAILING_SLASH,
    ),
  },
  {
    name: 'fields',
    urls: createDynamicUrls(
      CONFIG.siteUrl,
      '/field',
      fields.map((f) => f.id),
      '0.8',
      'monthly',
      CONFIG.languages,
      TRAILING_SLASH,
    ),
  },
]);
