#!/usr/bin/env python3
"""
JSON → D1 SQL Migration Generator

data/context/entries/*.json 파일을 읽어 D1 마이그레이션 SQL을 생성합니다.

사용법:
  # 특정 카테고리들만 변환
  python3 scripts/json-to-sql.py weather seasons animals

  # 모든 카테고리 변환
  python3 scripts/json-to-sql.py --all

  # 출력 파일 지정
  python3 scripts/json-to-sql.py weather --output apps/context/migrations/0007_update.sql

  # 검증만 (SQL 생성 없이 JSON 구조 확인)
  python3 scripts/json-to-sql.py weather --validate
"""

import json
import sys
import os
import argparse
from pathlib import Path

# 프로젝트 루트 기준 경로
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
ENTRIES_DIR = PROJECT_ROOT / "data" / "context" / "entries"
MIGRATIONS_DIR = PROJECT_ROOT / "apps" / "context" / "migrations"

# JSON 필드 → SQL 컬럼 매핑
FIELD_MAP = {
    "id": "id",
    "korean": "korean",
    "romanization": "romanization",
    "partOfSpeech": "part_of_speech",
    "categoryId": "category_id",
    "difficulty": "difficulty",
    "frequency": "frequency",
    "tags": "tags",
    "translations": "translations",
}

SQL_COLUMNS = list(FIELD_MAP.values())

REQUIRED_FIELDS = {"id", "korean", "categoryId"}


def escape_sql(value: str) -> str:
    """SQL 문자열 이스케이프 (싱글쿼트 → 더블 싱글쿼트)"""
    if value is None:
        return "NULL"
    return value.replace("'", "''")


def entry_to_sql_values(entry: dict) -> str:
    """단일 JSON 엔트리를 SQL VALUES 튜플 문자열로 변환"""
    values = []
    for json_field, sql_col in FIELD_MAP.items():
        raw = entry.get(json_field)

        if raw is None:
            values.append("NULL")
        elif json_field in ("tags", "translations"):
            # JSON 배열/객체 → 문자열로 직렬화
            json_str = json.dumps(raw, ensure_ascii=False, separators=(",", ":"))
            values.append(f"'{escape_sql(json_str)}'")
        else:
            values.append(f"'{escape_sql(str(raw))}'")

    return f"  ({', '.join(values)})"


def validate_entry(entry: dict, file_name: str, index: int) -> list[str]:
    """엔트리 유효성 검사, 에러 목록 반환"""
    errors = []
    for field in REQUIRED_FIELDS:
        if not entry.get(field):
            errors.append(f"  {file_name}[{index}]: 필수 필드 '{field}' 누락")

    entry_id = entry.get("id", "")
    if " " in entry_id or not entry_id.isascii():
        errors.append(f"  {file_name}[{index}]: id '{entry_id}'에 공백 또는 비ASCII 문자 포함")

    return errors


def load_entries(category_name: str) -> list[dict]:
    """카테고리 이름으로 JSON 파일 로드"""
    file_path = ENTRIES_DIR / f"{category_name}.json"
    if not file_path.exists():
        print(f"ERROR: 파일 없음: {file_path}", file=sys.stderr)
        sys.exit(1)

    with open(file_path, encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        print(f"ERROR: {file_path}는 배열이 아닙니다", file=sys.stderr)
        sys.exit(1)

    return data


def generate_sql(categories: list[str]) -> str:
    """여러 카테고리의 JSON → SQL 변환"""
    total_entries = 0
    category_counts = {}

    sql_parts = []

    for category in categories:
        entries = load_entries(category)
        category_counts[category] = len(entries)
        total_entries += len(entries)

        if not entries:
            continue

        values_list = []
        for entry in entries:
            values_list.append(entry_to_sql_values(entry))

        sql_parts.append(
            f"-- {category} ({len(entries)} entries)\n"
            f"INSERT OR REPLACE INTO entries ({', '.join(SQL_COLUMNS)}) VALUES\n"
            + ",\n".join(values_list)
            + ";\n"
        )

    # 헤더
    counts_summary = ", ".join(f"{c}: {n}" for c, n in category_counts.items())
    header = (
        f"-- Migration: Auto-generated from JSON data ({total_entries} entries)\n"
        f"-- Categories: {counts_summary}\n"
        f"-- Generated by: scripts/json-to-sql.py\n\n"
    )

    return header + "\n".join(sql_parts)


def validate_categories(categories: list[str]) -> bool:
    """모든 카테고리의 JSON 유효성 검사"""
    all_errors = []
    all_ids = set()
    duplicates = []

    for category in categories:
        entries = load_entries(category)
        for i, entry in enumerate(entries):
            errors = validate_entry(entry, f"{category}.json", i)
            all_errors.extend(errors)

            entry_id = entry.get("id", "")
            if entry_id in all_ids:
                duplicates.append(f"  중복 ID: '{entry_id}' (in {category}.json)")
            all_ids.add(entry_id)

    if all_errors:
        print("VALIDATION ERRORS:", file=sys.stderr)
        for err in all_errors:
            print(err, file=sys.stderr)

    if duplicates:
        print("DUPLICATE IDS:", file=sys.stderr)
        for dup in duplicates:
            print(dup, file=sys.stderr)

    total_issues = len(all_errors) + len(duplicates)
    if total_issues == 0:
        print(f"OK: {len(categories)} categories, {len(all_ids)} entries, 0 issues")
        return True
    else:
        print(f"FAILED: {total_issues} issues found", file=sys.stderr)
        return False


def get_all_categories() -> list[str]:
    """data/context/entries/ 디렉토리의 모든 카테고리 이름 반환"""
    return sorted(
        p.stem for p in ENTRIES_DIR.glob("*.json")
    )


def main():
    parser = argparse.ArgumentParser(
        description="JSON → D1 SQL Migration Generator"
    )
    parser.add_argument(
        "categories",
        nargs="*",
        help="변환할 카테고리 이름 (예: weather seasons animals)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="모든 카테고리 변환",
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        help="출력 SQL 파일 경로 (지정 안 하면 stdout)",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="검증만 실행 (SQL 생성 안 함)",
    )

    args = parser.parse_args()

    if args.all:
        categories = get_all_categories()
    elif args.categories:
        categories = args.categories
    else:
        parser.print_help()
        sys.exit(1)

    print(f"Categories: {', '.join(categories)} ({len(categories)} total)", file=sys.stderr)

    # 검증
    is_valid = validate_categories(categories)
    if args.validate:
        sys.exit(0 if is_valid else 1)

    if not is_valid:
        print("Validation failed. Fix errors before generating SQL.", file=sys.stderr)
        sys.exit(1)

    # SQL 생성
    sql = generate_sql(categories)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(sql)
        print(f"SQL written to: {output_path}", file=sys.stderr)
    else:
        print(sql)


if __name__ == "__main__":
    main()
