/**
 * Sitemap Generator for Permissive App
 */

import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createDynamicUrls, generateSitemaps, type StaticPage } from '@soundblue/seo/sitemap';

const __dirname = dirname(fileURLToPath(import.meta.url));

const CONFIG = {
  siteUrl: 'https://permissive.soundbluemusic.com',
  languages: ['en', 'ko'] as const,
  appName: 'Permissive',
  appSubtitle: 'Permissive - Free Web Dev Tools',
  outputDir: join(__dirname, '../public'),
};

const STATIC_PAGES: StaticPage[] = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/libraries', priority: '0.9', changefreq: 'weekly' },
  { path: '/web-api', priority: '0.9', changefreq: 'weekly' },
  { path: '/sitemap', priority: '0.5', changefreq: 'monthly' },
];

const LIBRARIES = [
  'react',
  'vue',
  'solid-js',
  'svelte',
  'preact',
  'alpine-js',
  'lit',
  'zustand',
  'jotai',
  'redux-toolkit',
  'pinia',
  'valtio',
  'mobx',
  'react-router',
  'tanstack-router',
  'vue-router',
  'tailwindcss',
  'unocss',
  'styled-components',
  'emotion',
  'panda-css',
  'vite',
  'esbuild',
  'rollup',
  'swc',
  'turbopack',
  'parcel',
  'tanstack-query',
  'swr',
  'axios',
  'ky',
  'radix-ui',
  'headless-ui',
  'shadcn-ui',
  'ark-ui',
  'framer-motion',
  'gsap',
  'lottie',
  'auto-animate',
  'react-hook-form',
  'formik',
  'zod',
  'yup',
  'date-fns',
  'dayjs',
  'lodash',
  'uuid',
  'nanoid',
  'localforage',
  'dexie-js',
  'idb',
  'idb-keyval',
  'pouchdb',
  'rxdb',
  'lokijs',
];

const WEB_APIS = [
  'document',
  'element',
  'event',
  'mutation-observer',
  'intersection-observer',
  'resize-observer',
  'fetch',
  'xmlhttprequest',
  'websocket',
  'server-sent-events',
  'beacon',
  'localstorage',
  'sessionstorage',
  'indexeddb',
  'cache-api',
  'canvas',
  'webgl',
  'webgpu',
  'svg',
  'web-audio',
  'media-recorder',
  'media-stream',
  'speech-synthesis',
  'speech-recognition',
  'web-workers',
  'service-workers',
  'shared-workers',
  'geolocation',
  'clipboard',
  'notifications',
  'vibration',
  'battery-status',
  'history',
  'url',
  'formdata',
  'crypto',
  'performance',
];

generateSitemaps(CONFIG, STATIC_PAGES, [
  {
    name: 'libraries',
    urls: createDynamicUrls(
      CONFIG.siteUrl,
      '/libraries',
      LIBRARIES,
      '0.7',
      'monthly',
      CONFIG.languages,
    ),
  },
  {
    name: 'webapi',
    urls: createDynamicUrls(
      CONFIG.siteUrl,
      '/web-api',
      WEB_APIS,
      '0.7',
      'monthly',
      CONFIG.languages,
    ),
  },
]);
